# Generated by Django 3.2 on 2023-06-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230601_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titlegenre',
            options={'ordering': ['title_id']},
        ),
        migrations.RenameField(
            model_name='titlegenre',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='titlegenre',
            old_name='title',
            new_name='title_id',
        ),
    ]
