# Generated by Django 3.2 on 2023-06-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20230601_2355'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='titlegenre',
            name='unique_title_genre',
        ),
    ]
